function spellChecker(a){this.popUpName="spellchecker";this.popUpProps="menu=no,width=440,height=350,top=70,left=120,resizable=yes,status=yes";this.replWordFlag="R";this.ignrWordFlag="I";this.replAllFlag="RA";this.ignrAllFlag="IA";this.fromReplAll="~RA";this.fromIgnrAll="~IA";this.wordFlags=[];this.currentWordIndex=this.currentTextIndex=0;this.wordWin=this.controlWin=this.spellCheckerWin=null;this.textArea=a;this.textInputs=arguments;this._editor="";this._spellcheck=_spellcheck;this._getSuggestions=
_getSuggestions;this._setAsIgnored=_setAsIgnored;this._getTotalReplaced=_getTotalReplaced;this._setWordText=_setWordText;this._getFormInputs=_getFormInputs;this.openChecker=openChecker;this.startCheck=startCheck;this.checkTextBoxes=checkTextBoxes;this.checkTextAreas=checkTextAreas;this.spellCheckAll=spellCheckAll;this.ignoreWord=ignoreWord;this.ignoreAll=ignoreAll;this.replaceWord=replaceWord;this.replaceAll=replaceAll;this.terminateSpell=terminateSpell;this.undo=undo;window.speller=this}
function checkTextBoxes(){this.textInputs=this._getFormInputs("^text$");this.openChecker()}function checkTextAreas(){this.textInputs=this._getFormInputs("^textarea$");this.openChecker()}function spellCheckAll(){this.textInputs=this._getFormInputs("^text(area)?$");this.openChecker()}function openChecker(){this.spellCheckerWin=window.open(this.popUpUrl,this.popUpName,this.popUpProps);if(!this.spellCheckerWin.opener)this.spellCheckerWin.opener=window}
function startCheck(a,b){this.wordWin=a;this.controlWin=b;this.wordWin.resetForm();this.controlWin.resetForm();this.currentWordIndex=this.currentTextIndex=0;this.wordFlags=Array(this.wordWin.textInputs.length);for(var d=0;d<this.wordFlags.length;d++)this.wordFlags[d]=[];this._spellcheck();return true}
function ignoreWord(){var a=this.currentWordIndex,b=this.currentTextIndex;if(!this.wordWin)return alert("Error: Word frame not available."),false;if(!this.wordWin.getTextVal(b,a))return alert('Error: "Not in dictionary" text is missing.'),false;this._setAsIgnored(b,a,this.ignrWordFlag)&&(this.currentWordIndex++,this._spellcheck())}
function ignoreAll(){var a=this.currentWordIndex,b=this.currentTextIndex;if(!this.wordWin)return alert("Error: Word frame not available."),false;var d=this.wordWin.getTextVal(b,a);if(!d)return alert('Error: "Not in dictionary" text is missing'),false;this._setAsIgnored(b,a,this.ignrAllFlag);for(var c=b;c<this.wordWin.textInputs.length;c++)for(var e=0;e<this.wordWin.totalWords(c);e++)(c==b&&e>a||c>b)&&this.wordWin.getTextVal(c,e)==d&&!this.wordFlags[c][e]&&this._setAsIgnored(c,e,this.fromIgnrAll);
this.currentWordIndex++;this._spellcheck()}function replaceWord(){var a=this.currentWordIndex,b=this.currentTextIndex;if(!this.wordWin)return alert("Error: Word frame not available."),false;if(!this.wordWin.getTextVal(b,a))return alert('Error: "Not in dictionary" text is missing'),false;if(this.controlWin.replacementText){var d=this.controlWin.replacementText;d.value&&(d=new String(d.value),this._setWordText(b,a,d,this.replWordFlag)&&(this.currentWordIndex++,this._spellcheck()))}}
function replaceAll(){var a=this.currentTextIndex,b=this.currentWordIndex;if(!this.wordWin)return alert("Error: Word frame not available."),false;var d=this.wordWin.getTextVal(a,b);if(!d)return alert('Error: "Not in dictionary" text is missing'),false;var c=this.controlWin.replacementText;if(c.value){c=new String(c.value);this._setWordText(a,b,c,this.replAllFlag);for(var e=a;e<this.wordWin.textInputs.length;e++)for(var f=0;f<this.wordWin.totalWords(e);f++)(e==a&&f>b||e>a)&&this.wordWin.getTextVal(e,
f)==d&&!this.wordFlags[e][f]&&this._setWordText(e,f,c,this.fromReplAll);this.currentWordIndex++;this._spellcheck()}}
function terminateSpell(){var a="Spell check complete:\n\n",b=this._getTotalReplaced();b==0?this.wordWin?a+=this.wordWin.totalMisspellings()?"No words changed.":"No misspellings found.":a="":a+=b==1?"One word changed.":b+" words changed.";a&&(a+="\n",alert(a));if(b>0){for(a=0;a<this.textInputs.length;a++)if(this.wordWin&&this.wordWin.textInputs[a])this.textInputs[a].value=this.wordWin.textInputs[a];try{this._editor.setHTML(this._editor._textArea.value)}catch(d){}}this.spellCheckerWin.close();return true}
function undo(){var a=this.currentTextIndex,b=this.currentWordIndex;if(this.wordWin.totalPreviousWords(a,b)>0){this.wordWin.removeFocus(a,b);do if(this.currentWordIndex==0&&this.currentTextIndex>0){if(this.currentTextIndex--,this.currentWordIndex=this.wordWin.totalWords(this.currentTextIndex)-1,this.currentWordIndex<0)this.currentWordIndex=0}else this.currentWordIndex>0&&this.currentWordIndex--;while(this.wordWin.totalWords(this.currentTextIndex)==0||this.wordFlags[this.currentTextIndex][this.currentWordIndex]==
this.fromIgnrAll||this.wordFlags[this.currentTextIndex][this.currentWordIndex]==this.fromReplAll);var a=this.currentTextIndex,b=this.currentWordIndex,d=this.wordWin.originalSpellings[a][b];this.wordWin.totalPreviousWords(a,b)==0&&this.controlWin.disableUndo();switch(this.wordFlags[a][b]){case this.replAllFlag:for(var c=a;c<this.wordWin.textInputs.length;c++)for(var e=0;e<this.wordWin.totalWords(c);e++)if(c==a&&e>=b||c>a){var f=this.wordWin.originalSpellings[c][e];f==d&&this._setWordText(c,e,f,void 0)}break;
case this.ignrAllFlag:for(c=a;c<this.wordWin.textInputs.length;c++)for(e=0;e<this.wordWin.totalWords(c);e++)if(c==a&&e>=b||c>a)f=this.wordWin.originalSpellings[c][e],f==d&&(this.wordFlags[c][e]=void 0);break;case this.replWordFlag:this._setWordText(a,b,d,void 0)}this.wordFlags[a][b]=void 0;this._spellcheck()}}
function _spellcheck(){var a=this.wordWin;if(this.currentWordIndex==a.totalWords(this.currentTextIndex))this.currentTextIndex++,this.currentWordIndex=0,this.currentTextIndex<this.wordWin.textInputs.length?this._spellcheck():this.terminateSpell();else if(this.currentWordIndex>0&&this.controlWin.enableUndo(),this.wordFlags[this.currentTextIndex][this.currentWordIndex])this.currentWordIndex++,this._spellcheck();else{var b=a.getTextVal(this.currentTextIndex,this.currentWordIndex);if(b)this.controlWin.evaluatedText.value=
b,a.setFocus(this.currentTextIndex,this.currentWordIndex),this._getSuggestions(this.currentTextIndex,this.currentWordIndex)}}function _getSuggestions(a,b){this.controlWin.clearSuggestions();var d=this.wordWin.suggestions[a][b];if(d)for(var c=0;c<d.length;c++)this.controlWin.addSuggestion(d[c]);this.controlWin.selectDefaultSuggestion()}function _setAsIgnored(a,b,d){this.wordWin.removeFocus(a,b);this.wordFlags[a][b]=d;return true}
function _getTotalReplaced(){for(var a=0,b=0;b<this.wordFlags.length;b++)for(var d=0;d<this.wordFlags[b].length;d++)(this.wordFlags[b][d]==this.replWordFlag||this.wordFlags[b][d]==this.replAllFlag||this.wordFlags[b][d]==this.fromReplAll)&&a++;return a}function _setWordText(a,b,d,c){this.wordWin.setText(a,b,d);this.wordFlags[a][b]=c;return true}
function _getFormInputs(a){for(var b=[],d=0;d<document.forms.length;d++)for(var c=0;c<document.forms[d].elements.length;c++)document.forms[d].elements[c].type.match(a)&&(b[b.length]=document.forms[d].elements[c]);return b};