function popupchecker(a){var b=window.open("itestwin.html","","width=1,height=1,left=0,top=0,scrollbars=no");b==null?alert(a):b.close()}function checkall(){for(var a=document.getElementsByTagName("input"),b=0;b<a.length;b++)if(a[b].type=="checkbox")a[b].checked=true}function checknone(){for(var a=document.getElementsByTagName("input"),b=0;b<a.length;b++)if(a[b].type=="checkbox")a[b].checked=false}
function lockoptions(a,b,c){a=document.forms[a];if(eval("form."+b+".checked"))for(i=0;i<c.length;i++)unlockoption(a,c[i]);else for(i=0;i<c.length;i++)lockoption(a,c[i]);return true}function lockoption(a,b){eval("form."+b+".disabled=true");a.elements["h"+b]&&eval("form.h"+b+".value=1")}function unlockoption(a,b){eval("form."+b+".disabled=false");a.elements["h"+b]&&eval("form.h"+b+".value=0")}
function get_form_element_value(a,b){var c=a[b];if(!c)return null;if(c.tagName)return c.value;for(var d=0;d<c.length;d++){var e=c[d];if(e.checked)return e.value}return null}function set_form_element_disabled(a,b,c){if(a=a[b]){if(a.tagName)a.disabled=c;for(b=0;b<a.length;b++)a[b].disabled=c}}
function lockoptionsall(a){var b=document.forms[a],a=eval(a+"items"),c=[],d;for(d in a)if(a.propertyIsEnumerable(d)&&b[d])for(var e in a[d])for(var f in a[d][e]){var h;switch(e){case "notchecked":h=!b[d].checked;break;case "checked":h=b[d].checked;break;case "noitemselected":h=b[d].selectedIndex==-1;break;case "eq":h=get_form_element_value(b,d)==f;break;default:h=get_form_element_value(b,d)!=f}for(var k in a[d][e][f])if(window.webkit||a[d][e][f].propertyIsEnumerable(k)){var g=a[d][e][f][k];c[g]=c[g]!=
null?h||c[g]:h}}for(var j in c)c.propertyIsEnumerable(j)&&set_form_element_disabled(b,j,c[j]);return true}
function lockoptionsallsetup(a){var b=document.forms[a],c=eval(a+"items"),d;for(d in c)if(c.propertyIsEnumerable(d)){var e=b[d];if(e){e.tagName&&(e=[e]);for(var f=0;f<e.length;f++)master=e[f],master.formid=a,master.onclick=function(){return lockoptionsall(this.formid)},master.onblur=function(){return lockoptionsall(this.formid)},master.onchange=function(){return lockoptionsall(this.formid)}}}for(c=0;c<b.elements.length;c++)if(d=b.elements[c],d.type=="reset")d.formid=a,d.onclick=function(){this.form.reset();
return lockoptionsall(this.formid)},d.onblur=function(){this.form.reset();return lockoptionsall(this.formid)},d.onchange=function(){this.form.reset();return lockoptionsall(this.formid)};return lockoptionsall(a)}function submitFormById(a){a=document.getElementById(a);if(!a)return false;if(a.tagName.toLowerCase()!="form")return false;if(!a.onsubmit||a.onsubmit())return a.submit()}
function select_all_in(a,b,c){for(var d=document.getElementsByTagName("input"),d=filterByParent(d,function(d){return findParentNode(d,a,b,c)}),e=0;e<d.length;++e)if(d[e].type=="checkbox"||d[e].type=="radio")d[e].checked="checked"}function deselect_all_in(a,b,c){for(var d=document.getElementsByTagName("INPUT"),d=filterByParent(d,function(d){return findParentNode(d,a,b,c)}),e=0;e<d.length;++e)if(d[e].type=="checkbox"||d[e].type=="radio")d[e].checked=""}
function confirm_if(a,b){return!a?true:confirm(b)}function findParentNode(a,b,c,d){for(;a.nodeName.toUpperCase()!="BODY";){if((!b||a.nodeName.toUpperCase()==b)&&(!c||a.className.indexOf(c)!=-1)&&(!d||a.id==d))break;a=a.parentNode}return a}
function findChildNodes(a,b,c,d,e){for(var f=[],h=0;h<a.childNodes.length;h++){var k=false,g=a.childNodes[h];if(g.nodeType==1&&c&&typeof g.className=="string"){var j=g.className.split(/\s+/),l;for(l in j)if(j[l]==c){k=true;break}}g.nodeType==1&&(f=(!b||g.nodeName==b)&&(!c||k)&&(!d||g.id==d)&&(!e||g.name==e)?f.concat(g):f.concat(findChildNodes(g,b,c,d,e)))}return f}
function elementShowAdvanced(a,b){for(var c in a)element=a[c],element.className=element.className.replace(/ ?hide/,""),b||(element.className+=" hide")}function showAdvancedInit(a,b,c,d,e){var f=document.createElement("input");f.type="button";f.value=c;f.name=b;f.moodle={hideLabel:d,showLabel:e};YAHOO.util.Event.addListener(f,"click",showAdvancedOnClick);el=document.getElementById(a);el.parentNode.insertBefore(f,el)}
function showAdvancedOnClick(a){var b=a.target?a.target:a.srcElement,c=findChildNodes(b.form,null,"advanced"),a="";b.form.elements.mform_showadvanced_last.value=="0"||b.form.elements.mform_showadvanced_last.value==""?(elementShowAdvanced(c,true),a=b.moodle.hideLabel,b.form.elements.mform_showadvanced_last.value="1"):(elementShowAdvanced(c,false),a=b.moodle.showLabel,b.form.elements.mform_showadvanced_last.value="0");b=b.form.elements;for(c=0;c<b.length;c++)if(b[c]&&b[c].name&&b[c].name=="mform_showadvanced")b[c].value=
a;return false}
function unmaskPassword(a){var b=document.getElementById(a),a=document.getElementById(a+"unmask");try{var c=a.checked?document.createElement('<input type="text" name="'+b.name+'">'):document.createElement('<input type="password" name="'+b.name+'">');c.attributes["class"].nodeValue=b.attributes["class"].nodeValue}catch(d){c=document.createElement("input"),c.setAttribute("name",b.name),a.checked?c.setAttribute("type","text"):c.setAttribute("type","password"),c.setAttribute("class",b.getAttribute("class"))}c.id=b.id;
c.size=b.size;c.onblur=b.onblur;c.onchange=b.onchange;c.value=b.value;b.parentNode.replaceChild(c,b)}
function elementToggleHide(a,b,c,d,e){c?c=c(a):(c=a,a=document.getElementById("togglehide_"+c.id));if(c.className.indexOf("hidden")==-1){c.className+=" hidden";if(a.src)a.src=a.src.replace("switch_minus","switch_plus"),a.alt=d,a.title=d;a=0}else{c.className=c.className.replace(/ ?hidden/,"");if(a.src)a.src=a.src.replace("switch_plus","switch_minus"),a.alt=e,a.title=e;a=1}b==true&&(new cookie("hide:"+c.id,1,a?-1:356,"/")).set()}
function elementCookieHide(a,b,c){var d=document.getElementById(a);(new cookie("hide:"+a)).read()!=null&&elementToggleHide(d,false,null,b,c)}function filterByParent(a,b){for(var c=[],d=0;d<a.length;++d)b(a[d]).nodeName!="BODY"&&c.push(a[d]);return c}function fix_column_widths(){var a=navigator.userAgent.toLowerCase();a.indexOf("msie")!=-1&&a.indexOf("opera")==-1&&(fix_column_width("left-column"),fix_column_width("right-column"))}
function fix_column_width(a){if(column=document.getElementById(a))if(column.offsetWidth){var a=0,b=column.childNodes;for(i=0;i<b.length;++i)if(b[i].className.indexOf("sideblock")!=-1&&a<b[i].offsetWidth)a=b[i].offsetWidth;for(i=0;i<b.length;++i)if(b[i].className.indexOf("sideblock")!=-1)b[i].style.width=a+"px"}else setTimeout("fix_column_width('"+a+"')",20)}
function insertAtCursor(a,b){if(document.selection)a.focus(),sel=document.selection.createRange(),sel.text=b;else if(a.selectionStart||a.selectionStart=="0"){var c=a.selectionEnd;a.value=a.value.substring(0,a.selectionStart)+b+a.value.substring(c,a.value.length)}else a.value+=b}function addonload(a){var b=window.onload;window.onload=function(){b&&b();a()}};
function uncheckall(){for(var b=document.getElementsByTagName("input"),a=0;a<b.length;a++)b[a].checked=false}function checkall(){for(var b=document.getElementsByTagName("input"),a=0;a<b.length;a++)b[a].checked=true}
function getElementsByClassName(b,a,c){var b=a=="*"&&b.all?b.all:b.getElementsByTagName(a),a=[],e=[];if(typeof c=="object")for(var d=0;d<c.length;d++)e.push(RegExp("(^|\\s)"+c[d].replace(/\-/g,"\\-")+"(\\s|$)"));else e.push(RegExp("(^|\\s)"+c.replace(/\-/g,"\\-")+"(\\s|$)"));for(var f=0;f<b.length;f++){for(var c=b[f],d=true,g=0;g<e.length;g++)if(!e[g].test(c.className)){d=false;break}d&&a.push(c)}return a};

// Make sure it plays with other js frameworks
jQuery.noConflict();
jQuery(document).ready(function(){
	setTimeout('fix_column_widths()', 20);
});